
import { Language } from '../types';

export const translations = {
  en: {
    nav: { divine: 'Divine', matches: 'Matches', boost: 'Boost', profile: 'Profile' },
    home: { finding: 'Finding your Divine match...', wait: 'Our AI is curating your best matches.', gold: 'GOLD', passed: 'Passed', liked: 'Liked', undo: 'Undo' },
    matches: { title: 'Matches', search: 'Search matches', new: 'New Matches', messages: 'Messages', noMsg: 'No messages yet. Get swiping!', matched: 'You matched! Say hello 👋', likes: 'Likes' },
    store: { title: 'Store', balance: 'YOUR BALANCE', getCoins: 'Get Coins', watchEarn: 'WATCH & EARN', freeCoins: 'Get 50 Free Coins', watchAd: 'Watch Ad', powerUps: 'Power Ups', spotlight: 'Spotlight', active: 'ACTIVE', superLike: '5 Super Likes', poweredBy: 'Powered by Google AdMob', spotlightDesc: 'Be the top profile in your area for 30m.', spotlightActive: 'Your profile is currently being shown to more people!', superLikeDesc: 'Stand out and get 3x more matches.' },
    profile: { language: 'Language', settings: 'SETTINGS', addMedia: 'ADD MEDIA', uploading: 'UPLOADING...', editInfo: 'EDIT INFO', completion: 'Profile Completion', myPhotos: 'My Photos', dragReorder: 'Drag to reorder', aboutMe: 'About Me', interests: 'Interests', add: 'Add', cancel: 'Cancel', save: 'Save', version: 'Version', bioPlaceholder: 'Tell us about yourself...', noBio: 'No bio yet. Tap the edit icon to add one!', completionMsg: 'Add more photos and interests to get up to 2x more matches.', completionFull: 'Great job! Your profile is fully optimized.', main: 'MAIN', delete: 'Delete', makeMain: 'Set as Main', selectLang: 'Select Language', age: 'Age', invalidAge: 'Please enter a valid age (18-99).', editCaption: 'Edit Caption', captionPlaceholder: 'Write a caption...', location: 'Location' },
    auth: { welcome: 'Welcome back', subtitle: 'Login to find your match', email: 'Email', password: 'Password', login: 'Log In', google: 'Sign in with Google', noAccount: "Don't have an account?", signup: 'Sign Up', createTitle: 'Create Account', createSubtitle: 'Join Divine today', name: 'Name', male: 'Male', female: 'Female', other: 'Other', gender: 'Gender', haveAccount: 'Already have an account?', continueWith: 'Or continue with' }
  },
  fr: {
    nav: { divine: 'Divine', matches: 'Matchs', boost: 'Boost', profile: 'Profil' },
    home: { finding: 'Recherche de votre partenaire...', wait: 'Notre IA sélectionne vos meilleurs profils.', gold: 'OR', passed: 'Passé', liked: 'Aimé', undo: 'Retour' },
    matches: { title: 'Matchs', search: 'Rechercher', new: 'Nouveaux Matchs', messages: 'Messages', noMsg: 'Pas encore de message.', matched: 'Ça matche ! Dites bonjour 👋', likes: 'J\'aime' },
    store: { title: 'Boutique', balance: 'VOTRE SOLDE', getCoins: 'Acheter', watchEarn: 'REGARDER & GAGNER', freeCoins: '50 Pièces Gratuites', watchAd: 'Regarder la pub', powerUps: 'Bonus', spotlight: 'Projecteur', active: 'ACTIF', superLike: '5 Super Likes', poweredBy: 'Propulsé par Google AdMob', spotlightDesc: 'Soyez le profil top de votre zone pendant 30m.', spotlightActive: 'Votre profil est vu par plus de gens !', superLikeDesc: 'Sortez du lot et obtenez 3x plus de matchs.' },
    profile: { language: 'Langue', settings: 'RÉGLAGES', addMedia: 'MÉDIAS', uploading: 'ENVOI...', editInfo: 'MODIFIER', completion: 'Profil complété', myPhotos: 'Mes Photos', dragReorder: 'Glisser pour réorganiser', aboutMe: 'À propos', interests: 'Intérêts', add: 'Ajouter', cancel: 'Annuler', save: 'Sauver', version: 'Version', bioPlaceholder: 'Parlez-nous de vous...', noBio: 'Pas de bio. Appuyez sur modifier !', completionMsg: 'Ajoutez des photos et intérêts pour 2x plus de matchs.', completionFull: 'Super ! Votre profil est optimisé.', main: 'PRINCIPAL', delete: 'Supprimer', makeMain: 'Définir principal', selectLang: 'Choisir la langue', age: 'Âge', invalidAge: 'Veuillez entrer un âge valide (18-99).', editCaption: 'Modifier la légende', captionPlaceholder: 'Écrire une légende...', location: 'Ville' },
    auth: { welcome: 'Bienvenue', subtitle: 'Connectez-vous pour rencontrer', email: 'Email', password: 'Mot de passe', login: 'Connexion', google: 'Continuer avec Google', noAccount: "Pas de compte ?", signup: 'S\'inscrire', createTitle: 'Créer un compte', createSubtitle: 'Rejoignez Divine aujourd\'hui', name: 'Nom', male: 'Homme', female: 'Femme', other: 'Autre', gender: 'Genre', haveAccount: 'Déjà un compte ?', continueWith: 'Ou continuer avec' }
  },
  sw: {
    nav: { divine: 'Divine', matches: 'Mechi', boost: 'Boost', profile: 'Wasifu' },
    home: { finding: 'Inatafuta mpenzi wako...', wait: 'AI yetu inakuchagulia mechi bora.', gold: 'DHAHABU', passed: 'Imepita', liked: 'Imependwa', undo: 'Tengua' },
    matches: { title: 'Mechi', search: 'Tafuta', new: 'Mechi Mpya', messages: 'Ujumbe', noMsg: 'Bado hakuna ujumbe.', matched: 'Umemepata mechi! Sema jambo 👋', likes: 'Vipendwa' },
    store: { title: 'Duka', balance: 'SALIO LAKO', getCoins: 'Pata Sarafu', watchEarn: 'TAZAMA & PATA', freeCoins: 'Sarafu 50 za Bure', watchAd: 'Tazama Tangazo', powerUps: 'Nguvu', spotlight: 'Mwangaza', active: 'IMEWASHWA', superLike: 'Super Likes 5', poweredBy: 'Imetolewa na Google AdMob', spotlightDesc: 'Kuwa wasifu wa juu katika eneo lako kwa 30m.', spotlightActive: 'Wasifu wako unaonyeshwa kwa watu wengi zaidi!', superLikeDesc: 'Simama na upate mechi mara 3 zaidi.' },
    profile: { language: 'Lugha', settings: 'MIPANGILIO', addMedia: 'ONGEZA MEDIA', uploading: 'INAPAKIA...', editInfo: 'BADILI', completion: 'Ukamilifu wa Wasifu', myPhotos: 'Picha Zangu', dragReorder: 'Buruta kupanga', aboutMe: 'Kuhusu Mimi', interests: 'Mambo Ninayopenda', add: 'Ongeza', cancel: 'Ghairi', save: 'Hifadhi', version: 'Toleo', bioPlaceholder: 'Tueleze kukuhusu...', noBio: 'Hakuna wasifu bado. Hariri kuongeza!', completionMsg: 'Ongeza picha na maslahi ili upate mechi zaidi.', completionFull: 'Kazi nzuri! Wasifu wako umekamilika.', main: 'KUU', delete: 'Futa', makeMain: 'Weka Kuu', selectLang: 'Chagua Lugha', age: 'Umri', invalidAge: 'Tafadhali weka umri halali (18-99).', editCaption: 'Hariri Maelezo', captionPlaceholder: 'Andika maelezo...', location: 'Mahali' },
    auth: { welcome: 'Karibu tena', subtitle: 'Ingia kupata mechi yako', email: 'Barua pepe', password: 'Nenosiri', login: 'Ingia', google: 'Endelea na Google', noAccount: "Huna akaunti?", signup: 'Jisajili', createTitle: 'Unda Akaunti', createSubtitle: 'Jiunge na Divine leo', name: 'Jina', male: 'Mwanaume', female: 'Mwanamke', other: 'Nyingine', gender: 'Jinsia', haveAccount: 'Una akaunti tayari?', continueWith: 'Au endelea na' }
  },
  ln: {
    nav: { divine: 'Divine', matches: 'Bato', boost: 'Boost', profile: 'Profil' },
    home: { finding: 'Koluka moto na yo...', wait: 'AI na biso ezali kopona bato.', gold: 'WOLO', passed: 'Eleki', liked: 'Elingami', undo: 'Zonga' },
    matches: { title: 'Bato', search: 'Luka', new: 'Bato ya sika', messages: 'Masolo', noMsg: 'Masolo ebandi te.', matched: 'Bokokani! Pesana mbote 👋', likes: 'Ba Likes' },
    store: { title: 'Zando', balance: 'MBONGO NA YO', getCoins: 'Zwa Mbongo', watchEarn: 'TALA & ZWA', freeCoins: 'Mbongo 50 ya ofele', watchAd: 'Tala Publicité', powerUps: 'Makasi', spotlight: 'Minda', active: 'EZA', superLike: '5 Super Likes', poweredBy: 'Na Google AdMob', spotlightDesc: 'Zala moto ya liboso na esika na yo po na 30m.', spotlightActive: 'Profil na yo ezali komonisama na bato ebele!', superLikeDesc: 'Bima na pole mpe zwa bato mbala 3.' },
    profile: { language: 'Lokota', settings: 'REGLAGES', addMedia: 'BA PHOTO', uploading: 'KOTINDA...', editInfo: 'KOBONGISA', completion: 'Profil esili', myPhotos: 'Ba Photo na ngai', dragReorder: 'Benda mpo na kobongisa', aboutMe: 'Mpo na ngai', interests: 'Bosepeli', add: 'Bakisa', cancel: 'Tika', save: 'Bomba', version: 'Version', bioPlaceholder: 'Lobela biso mwa moke...', noBio: 'Bio eza te. Finika po na kobakisa!', completionMsg: 'Bakisa ba photo mpe bosepeli mpo na kozwa bato.', completionFull: 'Malamu! Profil na yo ebongi.', main: 'LIBOSO', delete: 'Longola', makeMain: 'Tia ya Liboso', selectLang: 'Pona Lokota', age: 'Mibu', invalidAge: 'Mibu esengeli kozala kati ya 18 na 99.', editCaption: 'Bongisa Nkombo', captionPlaceholder: 'Koma nkombo...', location: 'Esika' },
    auth: { welcome: 'Boyeyi malamu', subtitle: 'Kota po na koluka moto', email: 'Imeli', password: 'Fungola (Mot de passe)', login: 'Kota', google: 'Kota na Google', noAccount: "Oza na compte te?", signup: 'Komikomisa', createTitle: 'Kela Compte', createSubtitle: 'Koma na Divine lelo', name: 'Kombo', male: 'Mobali', female: 'Mwasi', other: 'Mosusu', gender: 'Genre', haveAccount: 'Oza na compte?', continueWith: 'To landa na' }
  }
};
